language: go

sudo: false
install: true

go: "1.12"

script:
  - go vet ./...
  - go test -v -race ./...
  - go test -v -cover -covermode=count -coverprofile=coverage.txt ./... > /dev/null

after_success:
  - bash <(curl -s https://codecov.io/bash)
